language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "11"

# Use faster Docker architecture on Travis.
sudo: false

addons:
  postgresql: "9.6"

script:        travis_retry ./scripts/validate.sh
after_success: travis_retry npm run coveralls
