language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "stable"

# Use faster Docker architecture on Travis.
sudo: false

addons:
  postgresql: "9.6"

script:        ./scripts/validate.sh
after_success: npm run coveralls
