language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "stable"

# Use faster Docker architecture on Travis.
sudo: false

addons:
  postgresql: "10"
  packages:
    - postgresql-10
    - postgresql-client-10
services:
  - postgresql

before_script:
  - export PATH=/usr/lib/postgresql/10/bin:"$PATH":
script:        ./scripts/validate.sh
after_success: npm run coveralls
